### ISSUE TITLE
autoload conflict

### ISSUE THREAD

**Issue by proliteweb** [dshovchko/php_UAPAY#1]
Добрый день, установил пакет, композер пожаловался на одинаковый неймспей разных классов.
_Warning: Ambiguous class resolution, "UAPAY\Orders\Create\Response" was found in both "...vendor/dshovchko/php_uapay/src\Orders\Create\Response.php" and ".../vendor/dshovchko/php_uapay/src\Reports\Client\Response.php", the first will be used._
Я посмотрел, таки да, неймспес один.

**Comment by dshovchko** [comment]
Привет!
да copy/paste ошибка :(
постараюсь исправить на этой неделе

**Comment by proliteweb** [comment]
Можешь пожалуйста подсказать насчет платежки, я не могу въехать:
При создании сессии нужно передавать clientId - это ID магазина?
И насчет тестового платежа, там нужно регистрироваться отдельно на тестовом, там нужно также все реальные данные вводить или можно проще?

**Comment by dshovchko** [comment]
Да, clientId - это идентификатор клиента. Если у тебя магазин, то верно, это он. В кабинете можно посмотреть.

Насчет тестового лучше уточнить у менеджера. Я припоминаю что изначально включили тестовый энвайронмент, после того как мы все операции отработали на тестовом переключили нас на продакшен. Отличие тестового от продакшена в том что с карточек деньги не списываются. А еще был прикол, на тестовом TLS1.3 не требовался, а на проде потребовался. Был нежданчик...

**Comment by proliteweb** [comment]
Спасибо большое, а то и спросить не у кого, написал в саппорт, молчат пока)

**Comment by dshovchko** [comment]
А под какой версией php используется библиотека?

**Comment by proliteweb** [comment]
PHP 7.3 x64

**Comment by dshovchko** [comment]
исправлено
