### ISSUE TITLE
Установка ключа декодирования строкой

### ISSUE THREAD

**Issue by russelomua** [dshovchko/php_UAPAY#2]
Необходимо добавить возможность установки значений ключей, а не путей к файлам:
 - UAPAY_pubkey
 - our_privkey

**Comment by dshovchko** [comment]
Годная фича! Спасибо! Ваш PR заапрувал.
[Только вот тесты валятся](https://ibb.co/PxPr4Wz)

@russelomua, сможете поправить?

**Comment by russelomua** [comment]
Сейчас посмотрю

**Comment by russelomua** [comment]
Попроавил, в пул-реквесте обсуждение

**Comment by dshovchko** [comment]
Спасибо за оперативность!

**Comment by russelomua** [comment]
Тесты проходят, всё поправил.

**Comment by dshovchko** [comment]
Спасибо! Через пару дней будет релиз новой версии
